### ISSUE TITLE
Step 5 parameters did not work

### ISSUE THREAD

**Issue by Paul-jc** [OfficeDev/office-scripts-docs#400] opened 2021-09-17 04:08 UTC
Following this tutorial in step 5 it says to put 'Results' from the 'Run script' dynamic content in worksheetInformation.

When I did this the flow would fail with error code Office JS error: Line 7: Workbook addWorksheet: The argument is invalid or missing or has an incorrect format.
clientRequestId: b281f0ce-ed7a-4794-ac31-fb7abac1fbb5

I was able to fix get the worksheets to create by putting dynamic content 'name' from 'Run Sript' in the worksheetInformation parameter and 'data' in the worksheetInformation data Item Item - 1 parameter but the data is pasted as a string in a single cell.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688cb5b0-672f-8480-8943-6e4bc403d6b9
* Version Independent ID: 61518540-2796-b66f-4bc7-aef0eca420ad
* Content: [Combine workbooks into a single workbook - Office Scripts](https://docs.microsoft.com/en-gb/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook)
* Content Source: [docs/resources/samples/combine-worksheets-into-single-workbook.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/samples/combine-worksheets-into-single-workbook.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2021-09-17 16:48
Hi @Paul-jc,

Thanks for raising this issue. I believe the problem is that the default input for that `worksheetInformation` field is for individual elements of the 2D array (as you discovered with all the data going into one cell). There's an option in the upper-right corner of that field box to switch to passing the entire array. If you press that button, the connector will take in a single parameter and match the screenshot in the sample.

![image](https://user-images.githubusercontent.com/38896772/133824766-de0847c2-0776-4b15-ac3e-67ca80a85e47.png)

Does that fix the issue you're seeing?

**Comment by AlexJerabek** [comment] 2021-09-17 21:25
Hi @Paul-jc,

I created PR #401 to help highlight this step. Please let me know if this advice fixes your problem.

Thanks!

**Comment by Paul-jc** [comment] 2021-09-18 00:49
Thank you. I retried it, this time switching to the array input before selecting 'results' and it worked.

The order of these steps could be clearer.

**Comment by AlexJerabek** [comment] 2021-09-20 16:15
Agreed on the need for clear steps. I've added more instruction around that step:
![image](https://user-images.githubusercontent.com/38896772/134036782-793af51d-a91f-4d29-a7b1-dc1fb6953030.png)

Hopefully that helps, given the field and switch button only show up after you've selected a script.

These changes will soon be checked into the `master` branch of this repo and pushed to the `live` branch within 1-2 days..

**Closed by AlexJerabek** 2021-09-20 16:15 UTC
Labels: Needs: attention :wave:, Status: in PR, Type: doc bug
