### ISSUE TITLE
Script for folder location if not alert changed folder location

### ISSUE THREAD

**Issue by wongsunn** [OfficeDev/office-scripts-docs#569] opened 2023-01-11 02:56 UTC
[Enter feedback here]
Script to show Workbook location alert me to move this Workbook, if accidentally relocated, back to original folder; otherwise I would continue editing this Workbook under the impression it is still in original folder.

Windows 10 sync warning mark is always on because there are minor issues waiting for IT resolution. 
Unless there is a dedicated warning icon for sync, I am under risk missing sync warning unless I discipline myself to check for sync error.
Sync Error not only created inconvenience of unknowingly editing a copy of the original file (which was ,without warning, automatically relocated to Document Folder due to sync problem) which is input to my Microsoft Power Cloud Flow to fail.

sunny.wong@schindler.com
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98c58cbf-aaf7-3d3a-48f4-ce9cebcf331c
* Version Independent ID: 74821d34-eab6-ec0f-7a9f-55aca81975d9
* Content: [Basic scripts for Office Scripts in Excel - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-samples)
* Content Source: [docs/resources/samples/excel-samples.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/excel-samples.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2023-01-11 18:32
Hi @wongsunn,

Thank you for reaching out. I'm not quite sure I understand your issue. Are you saying that changing the Excel file in OneDrive causes a flow with that Excel file to fail? If so, I'm afraid that is the expected behavior. Power Automate's Excel connector uses file IDs to link to files. If a file is moved and moved back (or deleted and recreated with the same name), it's considered a different file.

Since this isn't an Office Scripts issue, I'd recommend heading over to the [Power Automate forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) and raising your concern there. 

I believe there's nothing actionable we can do here in the Office Scripts documentation, so I'm going to close this issue. Please let me know if I've misinterpreted things.

**Closed by AlexJerabek** 2023-01-11 18:32 UTC
Labels: Needs: triage :mag:

**Comment by wongsunn** [comment] 2023-01-12 04:12
> Hi @wongsunn,
> 
> Thank you for reaching out. I'm not quite sure I understand your issue. Are you saying that changing the Excel file in OneDrive causes a flow with that Excel file to fail? If so, I'm afraid that is the expected behavior. Power Automate's Excel connector uses file IDs to link to files. If a file is moved and moved back (or deleted and recreated with the same name), it's considered a different file.
> 
> Since this isn't an Office Scripts issue, I'd recommend heading over to the [Power Automate forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) and raising your concern there.
> 
> I believe there's nothing actionable we can do here in the Office Scripts documentation, so I'm going to close this issue. Please let me know if I've misinterpreted things.

Thanks, I mentioned Power Automate Flow that this script impacts on.  IMHO, this script make life easier not only for those who use Power Automate but also those who don't.
[https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-proceed-when-excel-without-autosave-is-in/0287f047-ed85-4dc7-80d5-d3e02b92a9fa](url)
