### ISSUE TITLE
Power Automate Run Excel Script task failed with error: "Range setValue: Timeout"

### ISSUE THREAD

**Issue by Rick-Maxinsheng** [OfficeDev/office-scripts-docs#580] opened 2023-02-15 07:35 UTC
## Article URL

https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/combine-worksheets-into-single-workbook.md

## Issue

I compose a simple Power Automate Flow for combining two Excel Workbooks by above two Office Scripts. The first script worked well to read the source file worksheet data, but the second one popped up an error when adding data into the destination workbook. The error is about the "range.setValues(value.data)" and feedback a Timeout. Some background information is that the source worksheet intended to be added contains more than 8000 rows. Please see the attached picture for detail. 

![OfficeScriptErr](https://user-images.githubusercontent.com/117808097/218961988-6da989ce-9a07-4cd4-b655-34f5c6f6cfbc.PNG)

**Comment by AlexJerabek** [comment] 2023-02-15 18:18
Hi @Rick-Maxinsheng,

I'm sorry to hear you're have trouble creating this flow. You have correctly identified the cause is that the workbook is large. Power Automate has a [120-second timeout for this operation](https://learn.microsoft.com/office/dev/scripts/testing/platform-limits#power-automate). The solution involves adding a loop to your flow that calls the scripts multiple times. I'm going to see if there's an existing example to share with you.

**Comment by Rick-Maxinsheng** [comment] 2023-02-16 01:55
Thank you very much, Alex. 
I will update my testing status once you have found the example

**Comment by AlexJerabek** [comment] 2023-02-23 00:14
Hi @Rick-Maxinsheng,

Just a quick update. It doesn't look like there's anything helpful to share, so I'm creating a new sample to illustrate this pattern. I should have something for you tomorrow.

**Comment by AlexJerabek** [comment] 2023-02-23 22:51
Hi @Rick-Maxinsheng,

I created PR #583 to help demonstrate how to avoid timeouts in Power Automate when working with large datasets. Does this help illustrate how to address the problem you're having?

**Comment by Rick-Maxinsheng** [comment] 2023-02-24 00:53
Thank you very much, Alex. That does shed light on my way.

**Comment by AlexJerabek** [comment] 2023-02-24 17:08
Glad to hear! I'll work on getting that sample checked in. This issue will automatically close when I do, but if you have further questions or feedback, please keep commenting.

**Closed** 2023-02-27 22:32 UTC
Labels: Status: in PR, Type: doc request
