### ISSUE TITLE
Error "Office JS error: Line 7: Workbook addWorksheet: A resource with the same name or identifier already exists. clientRequestId: 0e0da3f7-a61b-4618-a919-6b424ead5a19"

### ISSUE THREAD

**Issue by vile09** [OfficeDev/office-scripts-docs#560] opened 2022-12-20 15:47 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 688cb5b0-672f-8480-8943-6e4bc403d6b9
* Version Independent ID: 61518540-2796-b66f-4bc7-aef0eca420ad
* Content: [Combine workbooks into a single workbook - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook)
* Content Source: [docs/resources/samples/combine-worksheets-into-single-workbook.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/combine-worksheets-into-single-workbook.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment] 2022-12-20 17:46
Hi @vile09,
I'm sorry you encountered an error in the sample. I'll do some investigating today and get back to you about the cause of the problem and possible solutions.

**Comment by AlexJerabek** [comment] 2022-12-20 18:49
Hi @vile09,

Can you please clarify when you are getting this error? My thought is that this error occurs when you run the flow a second time. If you create a new workbook and use that for your "Add script 2" action, I don't think you'll get this error.

If this is the case, I'll make the sample instructions clearer.

**Comment by vile09** [comment] 2022-12-21 10:45
Hi @AlexJerabek, I've tried to create new workbook; new flow and now I got the error 'We were unable to run the script. Please try again.
Office JS error: Line 7: Workbook addWorksheet: The argument is invalid or missing or has an incorrect format.
clientRequestId: 439c80a4-cb41-49ab-9622-8ee509edd80e'. Can you help me to sort it out?

**Comment by vile09** [comment] 2022-12-21 10:57
I don't think this error is caused by the name of the file. Can you help to check and advise what is the root cause? Below is the screenshot of my file names in Onedrive folder.
![image](https://user-images.githubusercontent.com/75659581/208889311-7a117b16-0f38-482c-a114-1f72e88e2d83.png)

**Comment by AlexJerabek** [comment] 2022-12-21 22:02
Thanks @vile09. I think I understand both errors you've encountered. I'm using our conversation to rewrite the sample to be clearer and have some troubleshooting guidance. As for your errors, here are my thoughts.

- **Line 7: Workbook addWorksheet: A resource with the same name or identifier already exists.**: This happens when you run the flow a second time. If the workbook that's getting all the other worksheets already has worksheets with those names, this error is thrown.  You could have the script add a timestamp to the worksheet name to avoid duplicates, but I think you'll just run into the second error more. It's best to have a clean workbook collecting the data.
- **Line 7: Workbook addWorksheet: The argument is invalid or missing or has an incorrect format.**: This is happening because the file names in your test are longer than an [Excel worksheet name supports](https://support.microsoft.com/office/rename-a-worksheet-3f1f7148-ee83-404d-8ef0-9ff99fbad1f9). The workaround is to have the script trim the name. Please try this version of the Add worksheets script:
```
/**
 * This script creates a new worksheet in the current workbook for each WorksheetData object provided.
 */
function main(workbook: ExcelScript.Workbook, workbookName: string, worksheetInformation: WorksheetData[]) {
  // Add each new worksheet.
  worksheetInformation.forEach((value) => {
    let worksheetNumber = 1;
    let worksheetName = `${workbookName}.${value.name}`;
    let sheet = workbook.addWorksheet(`${worksheetName.substr(0,30)}${worksheetNumber++}`);

    // If there was any data in the worksheet, add it to a new range.
    if (value.data) {
      let range = sheet.getRangeByIndexes(0, 0, value.data.length, value.data[0].length);
      range.setValues(value.data);
    }
  });
}

// An interface to pass the worksheet name and cell values through a flow.
interface WorksheetData {
  name: string;
  data: string[][];
}
```

Please let me know if that solves your problem. I'll create a PR to improve this sample page with some of this guidance.

**Comment by vile09** [comment] 2022-12-23 07:34
Hi @AlexJerabek , thanks for your checking and explanation. 

Now I know what is the actual error of 'Line 7: Workbook addWorksheet: The argument is invalid or missing or has an incorrect format.'. Your provided code is still not working for my test case because the maximum worksheet name is 31 characters but my file name is too long (substr(0,30) can't help). So I shorten the file name, then it can work properly. Please help mention this on the sample page so other people can avoid this error. 

Wish you Merry Christmas and Have a happy new year!

**Comment by AlexJerabek** [comment] 2022-12-27 18:53
Thanks for checking that @vile09. I'll reopen this issue and close it once I've updated the documentation with that suggested note.

**Comment by AlexJerabek** [comment] 2022-12-27 22:54
Hi @vile09,

In case you can't shorten the workbook names, here's how you'd fix this problem.

Add an **Initialize variable** action before the flow (of **Type** "Integer") and an **Increment variable** action between the two **Run script** actions. Then, instead of using *Name* as the **workbookName** in "Run script 2", use the expression `substring(items('Apply_to_each')?['Name'],0,25)` and the dynamic content from your variable. This shortens the workbook names to 25 characters and appends the current workbook number to the string being passed to the script.

![image](https://user-images.githubusercontent.com/38896772/209732930-975303c3-0b17-436f-8e8f-4e81dba5cb01.png)

Combining the two name-shortening solutions results in workbook names like this:
![image](https://user-images.githubusercontent.com/38896772/209733297-2e3193af-7cd7-4638-9532-ec4d04a85d77.png)

**Closed** 2023-01-04 23:08 UTC
Labels: Status: in PR, Type: doc bug
